name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_lines: yes
          token: ${{ secrets.METRICS_TOKEN }}
#           committer_token: ${{ secrets.GITHUB_TOKEN }}
